[project]
name = "kcs-harness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "baesang", email = "baesang0522@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-core>=1.6.1",
    "langchain-deepseek>=1.1.0",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
    "uvicorn>=0.52.4",
]

